
staging:
  adapter: mysql2
  host: els.hamysql.prod.hulu.com
  username: hasql-woodenf_s
  password: SmkGiRT5e5ViXqpxqcf4y
  database: woodenf_s
  encoding: utf8
  pool: 5
  timeout: 5000

prod:
  adapter: mysql2
  host: els.hamysql.prod.hulu.com
  username: hasql-woodenfish
  password: SmkGiRT5e5ViXqpxqcf4y
  database: woodenfish
  encoding: utf8
  pool: 5
  timeout: 5000
