
staging:
  adapter: mysql2
  host: fake
  username: fake
  password: fake
  database: fake
  encoding: utf8
  pool: 5
  timeout: 5000

prod:
  adapter: mysql2
  host: fake
  username: fake
  password: fake
  database: fake
  encoding: utf8
  pool: 5
  timeout: 5000
