source "http://rubygems.org"

gem "mysql2"
gem "mail"
gem "nokogiri"

group :development do
  gem "rspec"
  gem "shoulda", ">= 0"
  gem "rdoc", "~> 3.12"
  gem "bundler"
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem "standalone_migrations"
end
